defaults:
  - training: default
  - representation: learned
  - model: smallnorb

representation: 
  name: smallnorb
  exp_num: 8700
  model: ann_vae
  exp_path:  path/to/disentanglement_lib-master/results/${representation.name}/${representation.model}/${representation.exp_num}
  representation_path: ${representation.exp_path}/postprocessed/mean/codes.npy
  factor_path: ${representation.exp_path}/postprocessed/mean/factors.npy
  fraction: 1
  num_workers: 4

hydra:
  run:
    dir: "output/${representation.name}/${now:%Y-%m-%d}_${now:%H-%M-%S}"
  job:
    chdir: True

training:
  wandb_project_name: ${representation.name}_${representation.model}_debug_${now:%Y-%m-%d}_${now:%H-%M-%S}
  num_epochs: 50
  lr: 0.0005
  debug: True
  optimizer: Adam
  log_iwo: True
  accelerator: cpu